### ISSUE TITLE
Can't sudo for apt-get

### ISSUE THREAD

**Issue by danielchalef** [sdt/docker-raspberry-pi-cross-compiler#12]
Need to install several packages, including git. The build user doesn't appear to be set up to sudo without a password, and I've been unsuccessful with finding a password that works.

**Comment by sdt** [comment]
The trick here is to create a downstream image based off rpxc that adds the packages you want, and then tell the rpxc wrapper script to use that image.

I've added an example which describes the process.

https://github.com/sdt/docker-raspberry-pi-cross-compiler/tree/master/examples/extra-packages

**Comment by sdt** [comment]
BTW, if there's packages which would be of general use, I'm open to adding those into the main image.

**Comment by danielchalef** [comment]
Perfect. Thanks for the primer on downstream images. My primary intention is a cx environment for ROS, OpenCV, and others. All of which can be a PITA compiling for optimization on the RPI2. Git would be a first candidate. I'll take note of what else I need.

**Comment by sdt** [comment]
Cheers!
