### ISSUE TITLE
Adding a sysroot for compilation?

### ISSUE THREAD

**Issue by meekrosoft** [sdt/docker-raspberry-pi-cross-compiler#15]
Hi,
Love the image!  But... is there a general guide to adding a sysroot to the image?  For instance, the jessie raspbian image?
https://downloads.raspberrypi.org/raspbian_latest
Cheers,
Mike

**Comment by sdt** [comment]
Hi Mike,
Glad you like it.

I've not used this for a little while - I've been off doing other things.

The whole sysroot directory thing is new to me. I'll take a look - I'm downloading the image now (it's large and coming down a little slowly).

Steve

**Comment by meekrosoft** [comment]
Cool!  Let me know if I can help in any way.

**Comment by sdt** [comment]
Sorry this has taken so long Mike.

I've done pretty much a complete rewrite on this. The new version has a raspbian jessie sysroot built-in, and an install-raspbian script which will install raspbian packages into it natively using chroot and qemu-arm-static.

If you want to use your own, right now there's two options:
1. create a downstream image and `COPY`/`ADD` your sysroot in directly
2. run with `RPXC_ARGS="-v /path/to/your/sysroot:/rpxc/sysroot"` which will mount your sysroot in place of the embedded one
