### ISSUE TITLE
make can't find dependencies

### ISSUE THREAD

**Issue by kowalcj0** [sdt/docker-raspberry-pi-cross-compiler#17]
Hi @sdt ,

I'm trying to build [CAVA](https://github.com/kowalcj0/cava/tree/build-for-arm-in-a-docker-container) for RPI 3, but somehow `make` can't find the dependencies, like: `libfftw3-dev & libasound2-dev` which I've added to the base image. See Dockerfile and `build-custom-docker-image-for-cava.sh` script.

I'm getting warning and error like this:

```
sudo ./rpxc --image rpxc-with-extras bash -c "ARCH=armv7l ./autogen.sh && ./configure --host=arm-linux-gnueabihf && make"
...
configure: WARNING: No alsa dev files found building without alsa support
checking for pa_simple_new in -lpulse-simple... no
configure: WARNING: No pusleaudio dev files found building without pulseaudio support
checking for sqrt in -lm... yes
checking for fftw_execute in -lfftw3... no
configure: error: fftw library is required!
```

Thanks
JK

**Comment by sdt** [comment]
Hi JK,

Cross-compiling can be a bit tricky when you need to add extra packages. Some of the packages need to be installed for the host system, and some are required for the target system.

I've got a [sadly neglected branch](https://github.com/sdt/docker-raspberry-pi-cross-compiler/tree/onbuild) that makes adding these packages a bit easier.

It's working quite well, I just got a little bogged down writing the documentation and examples, and never quite got back to it. Hopefully this might spur me along to finishing it up.

This version has an ONBUILD trigger that installs native and raspbian packages for you. 

You need to create two files, debian-packages.txt and raspbian-packages.txt. These list the host and target packages, one perl line. You then do a `docker build` and the ONBUILD trigger will install the listed packaged.

The raspbian package installation is a bit of a hack, but it seems to work okay. I suspect there is a less hacky way, but that's a battle for another day.

I've built and pushed a docker image from this branch `sdt4docker/raspberry-pi-cross-compiler:cava-testing`, and have set up the package files needed to build cava. See: https://github.com/sdt/cava/commit/94369dcedca1ffd3ad69ec2fe371e1404a367f66

There's a script called `rpxc-build` which will run `autogen.sh`, `configure` and `make` with the appropriate options.

Note that `configure` needs a couple of extra arguments. This is typical when cross-compiling. If you run `rpxc env` you'll see a few environment variables (like $HOST) intended to make this easier.

This builds cava successfully for me. I notice though that it doesn't quite link libiniparser.so properly. You're left with a partially-linked `.lib/cava` file, and `cava` itself is a wrapper shell script. I get this same behaviour when building natively on my raspberry pi, so it looks like an upstream issue.

**Comment by sdt** [comment]
BTW, I notice you're using `sudo` in your examples above. If you add yourself to the `docker` group, you should be able to run docker without the `sudo`.

**Comment by kowalcj0** [comment]
Hi @sdt 

WOW! Thank you for your response and help. I'll give it a go tonight or tomorrow.

ps. I'm already a member of the `docker` group
```
jk@home:~ 22:19:38 $ groups
jk adm cdrom sudo dip plugdev lpadmin sambashare docker
```
When I omit `sudo` then I'm getting error like this:
```
$ ./rpxc --image rpxc-with-extras bash -c "./autogen.sh && ./configure --host=arm-linux-gnueabihf && make"
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
mkdir: cannot create directory '/root': Permission denied
cp: failed to access '/root/.config/cava/config': Permission denied
```

Thanks

**Comment by sdt** [comment]
Closing as part of an old issue tidy-up. Please create a new issue if necessary.
